import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

import {ContactForm} from "../components/ContactForm";
import { BookConsultation } from "@/components/BookConsultation";
import Footer from "@/components/Footer";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}
        <div>
<Header/>
       
        {children}
        <BookConsultation />
        <ContactForm />
        <Footer/>
        </div>
        </body>
    </html>
  );
}
